DELETE FROM PETS;
DELETE FROM USERS;
DELETE FROM TYPES;
DELETE FROM fail_attempts;

INSERT INTO TYPES (ID, NAME) VALUES (101, 'Cat');
INSERT INTO TYPES (ID, NAME) VALUES (102, 'Dog');
INSERT INTO TYPES (ID, NAME) VALUES (103, 'Rabbit');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (101, 'admin', '$2a$12$LrWCy0SSCYNTovkxy3yau.4lvKKC3jMWC6HKmwF9F99jxLoKXaO/K', 'ADMIN');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (102, 'user', '$2a$12$6gjgTswiLOubRSn8xRYXeuKOEF/g1NPIGubJ90Hou9iC7c4du6Kim', 'USER');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (103, 'user2', '$2a$12$UNnuZTSaZbsJj9IPQdpaD.geLxMhvZLkYaEjU6czjetxhlmnF3ctS', 'USER');
INSERT INTO PETS (ID, NAME, TYPE_ID, GENDER, BIRTHDATE, OWNER_ID) VALUES (101, 'Murka', 101, 'FEMAIL', '2020-05-20', 102);
INSERT INTO PETS (ID, NAME, TYPE_ID, GENDER, BIRTHDATE, OWNER_ID) VALUES (102, 'Bobik', 102, 'MAIL', '2019-04-10', 102);
INSERT INTO PETS (ID, NAME, TYPE_ID, GENDER, BIRTHDATE, OWNER_ID) VALUES (103, 'Roger', 103, 'MAIL', '1988-06-21', 103);