DROP TABLE IF EXISTS FAIL_ATTEMPTS CASCADE;
DROP TABLE IF EXISTS PETS CASCADE;
DROP TABLE IF EXISTS TYPES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE FAIL_ATTEMPTS (
    ID BIGSERIAL NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    ATTEMPT_TIME TIMESTAMP,
    PRIMARY KEY (ID));

CREATE TABLE USERS (
    ID BIGSERIAL NOT NULL,
    USERNAME VARCHAR(25) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID));
    
CREATE TABLE TYPES (
    ID BIGSERIAL NOT NULL,
    NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID), 
    UNIQUE(NAME));

CREATE TABLE PETS (
    ID BIGSERIAL NOT NULL, 
    TYPE_ID int8 NOT NULL,
    NAME VARCHAR(25) NOT NULL,
    GENDER VARCHAR(6) NOT NULL,
    BIRTHDATE date, 
    OWNER_ID int8 NOT NULL,
    PRIMARY KEY (ID));  

ALTER TABLE TYPES ADD CONSTRAINT UK_TYPES_NAME UNIQUE (NAME);
ALTER TABLE USERS ADD CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME);
ALTER TABLE PETS ADD CONSTRAINT UK_PETS_OWNERID_AND_NAME UNIQUE (OWNER_ID, NAME);
ALTER TABLE PETS ADD CONSTRAINT FK_PETS_OWNERID FOREIGN KEY (OWNER_ID) REFERENCES USERS (ID);
ALTER TABLE PETS ADD CONSTRAINT FK_PETS_TYPEID FOREIGN KEY (TYPE_ID) REFERENCES TYPES(ID);