INSERT INTO TYPES (ID, NAME) VALUES (1, 'Cat');
INSERT INTO TYPES (ID, NAME) VALUES (2, 'Dog');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (1, 'admin', '$2a$12$LrWCy0SSCYNTovkxy3yau.4lvKKC3jMWC6HKmwF9F99jxLoKXaO/K', 'ADMIN');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (2, 'user', '$2a$12$6gjgTswiLOubRSn8xRYXeuKOEF/g1NPIGubJ90Hou9iC7c4du6Kim', 'USER');
INSERT INTO PETS (ID, NAME, TYPE_ID, GENDER, BIRTHDATE, OWNER_ID) VALUES (1, 'MURCA', 1, 'FEMAIL', '2020-05-20', 2);
INSERT INTO PETS (ID, NAME, TYPE_ID, GENDER, BIRTHDATE, OWNER_ID) VALUES (2, 'BOBIK', 2, 'MAIL', '2019-04-10', 2);

SELECT setval('types_id_seq', 10, true);
SELECT setval('users_id_seq', 10, true);
SELECT setval('pets_id_seq', 10, true);